name: Sync Fork

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: NixOS
          base: unstable-good 
          head: nixos-unstable 
