name: Sync Fork

on:
  schedule:
    - cron:  '0 */1 * * *'
  workflow_dispatch: # on button click

jobs:
  unstable-good:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: NixOS
          base: unstable-good
          head: nixos-unstable
          retries: 0
          retryAfter: 2
  nixos-unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: NixOS
          base: nixos-unstable
          head: nixos-unstable
          retries: 0
          retryAfter: 2
  jhoffer-22_11:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: NixOS
          base: jhoffer-22.11
          head: nixos-22.11
          retries: 0
          retryAfter: 2
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: NixOS
          base: master
          head: master
          retries: 0
          retryAfter: 2
